name: ServerSupport
version: ${project.version}
main: poti.serversupport.ServerSupport
api-version: 1.16

commands:
  ChatClear:
    description: チャットをクリアします
  get:
    description: IPアドレスとUUIDを取得します
  fly:
    description: Flyをすることができます

